---
Name: graphql-dev
---
SilverStripe\Dev\Command\DbBuild:
  extensions:
    - SilverStripe\GraphQL\Extensions\DbBuildExtension

SilverStripe\Dev\DevelopmentAdmin:
  commands:
    'graphql/build': 'SilverStripe\GraphQL\Dev\SchemaBuild'
